# Generated by Django 5.2.6 on 2026-08-28 15:42

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicSession',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('code', models.CharField(db_index=True, max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_active', models.BooleanField(db_index=True, default=False)),
                ('is_archived', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'programs_academic_session',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='MasterData',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('ACADEMIC_DEPT', 'Academic Department'), ('ADMIN_DEPT', 'Administrative Department'), ('DESIGNATION', 'Designation'), ('PROGRAM_TYPE', 'Program Type'), ('PROGRAM_CATEGORY', 'Program Category'), ('VENUE', 'Venue'), ('RESOURCE_PERSON', 'Resource Person'), ('PARTICIPANT_TYPE', 'Participant Type'), ('INSTITUTION_TYPE', 'Institution Type'), ('QUESTION_TYPE', 'Question Type'), ('CERTIFICATE_TYPE', 'Certificate Type'), ('FOOD_TYPE', 'Food Type')], db_index=True, max_length=30)),
                ('code', models.CharField(db_index=True, max_length=50)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'programs_master_data',
                'ordering': ['category', 'sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('title', models.CharField(max_length=300)),
                ('short_code', models.CharField(db_index=True, max_length=20, unique=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('number_of_days', models.PositiveIntegerField(default=1)),
                ('venue_details', models.TextField(blank=True)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('max_participants', models.PositiveIntegerField(blank=True, null=True)),
                ('objective', models.TextField(blank=True)),
                ('expected_outcomes', models.TextField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('contact_info', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published'), ('REG_OPEN', 'Registration Open'), ('REG_CLOSED', 'Registration Closed'), ('ONGOING', 'Ongoing'), ('COMPLETED', 'Completed'), ('ARCHIVED', 'Archived'), ('CANCELLED', 'Cancelled'), ('POSTPONED', 'Postponed'), ('RESCHEDULED', 'Rescheduled')], db_index=True, default='DRAFT', max_length=20)),
                ('registration_requires_approval', models.BooleanField(default=False)),
                ('registration_identity_key', models.JSONField(blank=True, default=list, help_text="Fields that uniquely identify a participant (e.g., ['email'] or ['email', 'mobile'])")),
                ('registration_schema', models.JSONField(blank=True, default=dict)),
                ('feedback_schema', models.JSONField(blank=True, default=dict)),
                ('certificate_eligibility_rule', models.JSONField(blank=True, default=dict, help_text="e.g., {'type': 'attendance_percentage', 'value': 75} or {'type': 'days_present', 'min_days': 3}")),
                ('public_token', models.CharField(blank=True, db_index=True, max_length=64, unique=True)),
                ('public_link_enabled', models.BooleanField(default=True)),
                ('registration_link_enabled', models.BooleanField(default=True)),
                ('feedback_link_enabled', models.BooleanField(default=False)),
                ('academic_session', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='programs', to='programs.academicsession')),
                ('certificate_template', models.ForeignKey(blank=True, limit_choices_to={'category': 'CERTIFICATE_TYPE'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certificate_programs', to='programs.masterdata')),
                ('collaborating_departments', models.ManyToManyField(blank=True, limit_choices_to={'category': 'ACADEMIC_DEPT'}, related_name='collaborated_programs', to='programs.masterdata')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('organizing_department', models.ForeignKey(limit_choices_to={'category': 'ACADEMIC_DEPT'}, on_delete=django.db.models.deletion.PROTECT, related_name='organized_programs', to='programs.masterdata')),
                ('program_category', models.ForeignKey(blank=True, limit_choices_to={'category': 'PROGRAM_CATEGORY'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='programs_by_category', to='programs.masterdata')),
                ('program_coordinator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='coordinated_programs', to=settings.AUTH_USER_MODEL)),
                ('program_type', models.ForeignKey(limit_choices_to={'category': 'PROGRAM_TYPE'}, on_delete=django.db.models.deletion.PROTECT, related_name='programs_by_type', to='programs.masterdata')),
                ('resource_persons', models.ManyToManyField(blank=True, limit_choices_to={'category': 'RESOURCE_PERSON'}, related_name='resource_programs', to='programs.masterdata')),
                ('target_departments', models.ManyToManyField(blank=True, limit_choices_to={'category': 'ACADEMIC_DEPT'}, related_name='targeted_programs', to='programs.masterdata')),
                ('target_participant_types', models.ManyToManyField(blank=True, limit_choices_to={'category': 'PARTICIPANT_TYPE'}, related_name='target_programs', to='programs.masterdata')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('venue', models.ForeignKey(blank=True, limit_choices_to={'category': 'VENUE'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='programs_at_venue', to='programs.masterdata')),
            ],
            options={
                'db_table': 'programs_program',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='ProgramAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('SA', 'System Administrator'), ('PA', 'Program Administrator (IQAC Coordinator)'), ('PC', 'Program Coordinator'), ('AO', 'Attendance Operator'), ('FO', 'Food Counter Operator'), ('V', 'Viewer / Reporting User')], default='PC', max_length=2, verbose_name='role')),
                ('is_active', models.BooleanField(default=True)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_program_roles', to=settings.AUTH_USER_MODEL)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='programs.program')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='program_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'programs_program_assignment',
            },
        ),
        migrations.CreateModel(
            name='ProgramDay',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('day_number', models.PositiveIntegerField()),
                ('date', models.DateField(db_index=True)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('is_cancelled', models.BooleanField(default=False)),
                ('cancellation_reason', models.TextField(blank=True)),
                ('attendance_enabled', models.BooleanField(default=True)),
                ('food_enabled', models.BooleanField(default=False)),
                ('feedback_enabled', models.BooleanField(default=False)),
                ('quiz_enabled', models.BooleanField(default=False)),
                ('other_enabled', models.BooleanField(default=False)),
                ('other_description', models.CharField(blank=True, max_length=200)),
                ('food_eligibility_rule', models.JSONField(blank=True, default=dict, help_text="e.g., {'type': 'attendance_present'} or {'type': 'attendance_percentage', 'value': 50}")),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('food_type', models.ForeignKey(blank=True, limit_choices_to={'category': 'FOOD_TYPE'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='food_program_days', to='programs.masterdata')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to='programs.program')),
                ('resource_persons', models.ManyToManyField(blank=True, limit_choices_to={'category': 'RESOURCE_PERSON'}, related_name='program_days', to='programs.masterdata')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'programs_program_day',
                'ordering': ['program', 'day_number'],
            },
        ),
        migrations.CreateModel(
            name='ProgramServiceConfig',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('service_type', models.CharField(choices=[('ATTENDANCE', 'Attendance'), ('FOOD', 'Food'), ('FEEDBACK', 'Feedback'), ('QUIZ', 'Quiz'), ('OTHER', 'Other')], db_index=True, max_length=20)),
                ('is_enabled', models.BooleanField(default=True)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('ACTIVE', 'Active'), ('CLOSED', 'Closed'), ('DISABLED', 'Disabled')], db_index=True, default='SCHEDULED', max_length=20)),
                ('opens_at', models.DateTimeField(blank=True, null=True)),
                ('closes_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('day', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service_configs', to='programs.programday')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_configs', to='programs.program')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'programs_service_config',
            },
        ),
        migrations.AddConstraint(
            model_name='academicsession',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('is_active',), name='unique_active_session'),
        ),
        migrations.AddIndex(
            model_name='masterdata',
            index=models.Index(fields=['category', 'is_active'], name='programs_ma_categor_df607f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='masterdata',
            unique_together={('category', 'code')},
        ),
        migrations.AddIndex(
            model_name='program',
            index=models.Index(fields=['status', 'academic_session'], name='programs_pr_status_4b9139_idx'),
        ),
        migrations.AddIndex(
            model_name='program',
            index=models.Index(fields=['organizing_department', 'status'], name='programs_pr_organiz_0f02f9_idx'),
        ),
        migrations.AddIndex(
            model_name='program',
            index=models.Index(fields=['program_coordinator', 'status'], name='programs_pr_program_9b99a6_idx'),
        ),
        migrations.AddIndex(
            model_name='programassignment',
            index=models.Index(fields=['user', 'is_active'], name='programs_pr_user_id_840aca_idx'),
        ),
        migrations.AddIndex(
            model_name='programassignment',
            index=models.Index(fields=['program', 'is_active'], name='programs_pr_program_bc1855_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='programassignment',
            unique_together={('user', 'program', 'role')},
        ),
        migrations.AddIndex(
            model_name='programday',
            index=models.Index(fields=['program', 'date'], name='programs_pr_program_58918d_idx'),
        ),
        migrations.AddIndex(
            model_name='programday',
            index=models.Index(fields=['date', 'attendance_enabled'], name='programs_pr_date_0d6686_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='programday',
            unique_together={('program', 'day_number')},
        ),
        migrations.AddIndex(
            model_name='programserviceconfig',
            index=models.Index(fields=['program', 'service_type', 'status'], name='programs_se_program_22ed11_idx'),
        ),
        migrations.AddIndex(
            model_name='programserviceconfig',
            index=models.Index(fields=['day', 'service_type', 'status'], name='programs_se_day_id_7a85bb_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='programserviceconfig',
            unique_together={('program', 'day', 'service_type')},
        ),
    ]
