# Generated by Django 5.2.6 on 2026-08-29 01:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0002_alter_participant_department_and_more'),
        ('programs', '0002_alter_masterdata_unique_together_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MasterData',
        ),
    ]
