# Generated by Django 5.2.6 on 2026-08-29 02:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0003_delete_masterdata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='academicdepartment',
            name='college',
        ),
    ]
