# Generated by Django 5.2.6 on 2026-08-29 02:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0004_remove_academicdepartment_college'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='program',
            name='program_category',
        ),
        migrations.DeleteModel(
            name='ProgramCategory',
        ),
    ]
