# Generated by Django 5.2.6 on 2026-08-29 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0005_remove_program_program_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='designation',
            name='category',
        ),
        migrations.AddField(
            model_name='designation',
            name='staff_type',
            field=models.CharField(choices=[('Teaching', 'Teaching'), ('Non-Teaching', 'Non-Teaching'), ('Student', 'Student')], default='Teaching', help_text='Teaching, Non-Teaching or Student', max_length=20),
        ),
    ]
