# Generated by Django 5.2.6 on 2026-08-29 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0006_remove_designation_category_designation_staff_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='designation',
            name='staff_type',
            field=models.CharField(choices=[('Teaching', 'Teaching'), ('Non-Teaching', 'Non-Teaching')], default='Teaching', help_text='Teaching or Non-Teaching (Student is a Non-Teaching designation)', max_length=20),
        ),
    ]
