# Generated by Django 5.2.6 on 2026-08-30 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0003_remove_participant_participant_partici_a4c252_idx_and_more'),
        ('programs', '0007_alter_designation_staff_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='program',
            name='certificate_template',
        ),
        migrations.AlterUniqueTogether(
            name='institutiontype',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='institutiontype',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='institutiontype',
            name='updated_by',
        ),
        migrations.AlterUniqueTogether(
            name='participanttype',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='participanttype',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='participanttype',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='program',
            name='target_participant_types',
        ),
        migrations.AlterUniqueTogether(
            name='resourceperson',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='resourceperson',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='resourceperson',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='program',
            name='resource_persons',
        ),
        migrations.RemoveField(
            model_name='programday',
            name='resource_persons',
        ),
        migrations.RemoveField(
            model_name='designation',
            name='rank',
        ),
        migrations.DeleteModel(
            name='CertificateType',
        ),
        migrations.DeleteModel(
            name='InstitutionType',
        ),
        migrations.DeleteModel(
            name='ParticipantType',
        ),
        migrations.DeleteModel(
            name='ResourcePerson',
        ),
        migrations.AddField(
            model_name='programday',
            name='resource_persons',
            field=models.JSONField(blank=True, default=list, help_text='List of {name, designation, institution, email, phone} for resource persons on this day'),
        ),
    ]
