# Generated by Django 5.2.6 on 2026-09-01 01:12

from django.db import migrations, models

# Snapshot of legacy single organizing_department FK values (program_id -> dept_id)
_LegacyOrg = []


def snapshot_legacy(apps, schema_editor):
    Program = apps.get_model('programs', 'Program')
    _LegacyOrg[:] = []
    for p in Program.objects.all():
        if p.organizing_department_id:
            _LegacyOrg.append((str(p.id), str(p.organizing_department_id)))


def restore_organizing(apps, schema_editor):
    Program = apps.get_model('programs', 'Program')
    for pid, dept_id in _LegacyOrg:
        try:
            program = Program.objects.get(pk=pid)
        except Program.DoesNotExist:
            continue
        program.organizing_departments.add(dept_id)


def restore_organizing_reverse(apps, schema_editor):
    pass


def snapshot_legacy_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0008_remove_program_certificate_template_and_more'),
    ]

    operations = [
        migrations.RunPython(snapshot_legacy, snapshot_legacy_reverse),
        migrations.RemoveIndex(
            model_name='program',
            name='programs_pr_organiz_0f02f9_idx',
        ),
        migrations.RemoveField(
            model_name='program',
            name='organizing_department',
        ),
        migrations.AddField(
            model_name='program',
            name='organizing_departments',
            field=models.ManyToManyField(blank=True, related_name='organized_programs', to='programs.academicdepartment'),
        ),
        migrations.RunPython(restore_organizing, restore_organizing_reverse),
    ]
