# Generated by Django 5.2.6 on 2026-09-05 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0009_remove_program_programs_pr_organiz_0f02f9_idx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programday',
            name='feedback_enabled',
        ),
    ]
