# Generated by Django 5.2.6 on 2026-08-28 15:42

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('programs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportPreset',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('report_type', models.CharField(choices=[('REGISTRATION', 'Registration Report'), ('ATTENDANCE', 'Attendance Report'), ('FOOD', 'Food Distribution Report'), ('FEEDBACK', 'Feedback Report'), ('CERTIFICATE', 'Certificate Report'), ('PARTICIPANT_STATUS', 'Participant Status Matrix'), ('COMPLETE_PROGRAM', 'Complete Program Report'), ('DEPARTMENT_WISE', 'Department-wise Report'), ('ACADEMIC_SESSION', 'Academic Session Analysis'), ('CUSTOM', 'Custom Report')], db_index=True, max_length=30)),
                ('selected_columns', models.JSONField(default=list)),
                ('filters', models.JSONField(blank=True, default=dict)),
                ('sorting', models.JSONField(blank=True, default=list)),
                ('is_global', models.BooleanField(default=False)),
                ('is_shared', models.BooleanField(default=False)),
                ('academic_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='report_presets', to='programs.academicsession')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_report_presets', to=settings.AUTH_USER_MODEL)),
                ('program', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='report_presets', to='programs.program')),
                ('shared_with', models.ManyToManyField(blank=True, related_name='shared_report_presets', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'report_preset',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReportColumn',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('report_type', models.CharField(choices=[('REGISTRATION', 'Registration Report'), ('ATTENDANCE', 'Attendance Report'), ('FOOD', 'Food Distribution Report'), ('FEEDBACK', 'Feedback Report'), ('CERTIFICATE', 'Certificate Report'), ('PARTICIPANT_STATUS', 'Participant Status Matrix'), ('COMPLETE_PROGRAM', 'Complete Program Report'), ('DEPARTMENT_WISE', 'Department-wise Report'), ('ACADEMIC_SESSION', 'Academic Session Analysis'), ('CUSTOM', 'Custom Report')], db_index=True, max_length=30)),
                ('field_name', models.CharField(max_length=100)),
                ('display_name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('data_type', models.CharField(choices=[('string', 'String'), ('number', 'Number'), ('date', 'Date'), ('datetime', 'DateTime'), ('boolean', 'Boolean'), ('json', 'JSON')], default='string', max_length=20)),
                ('is_default', models.BooleanField(default=False)),
                ('is_pii', models.BooleanField(default=False)),
                ('sort_order', models.IntegerField(default=0)),
                ('depends_on', models.JSONField(blank=True, default=dict, help_text="Configuration dependencies, e.g., {'food_enabled': true} for food columns")),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'report_column',
                'ordering': ['report_type', 'sort_order'],
                'unique_together': {('report_type', 'field_name')},
            },
        ),
        migrations.CreateModel(
            name='ReportExport',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('report_type', models.CharField(choices=[('REGISTRATION', 'Registration Report'), ('ATTENDANCE', 'Attendance Report'), ('FOOD', 'Food Distribution Report'), ('FEEDBACK', 'Feedback Report'), ('CERTIFICATE', 'Certificate Report'), ('PARTICIPANT_STATUS', 'Participant Status Matrix'), ('COMPLETE_PROGRAM', 'Complete Program Report'), ('DEPARTMENT_WISE', 'Department-wise Report'), ('ACADEMIC_SESSION', 'Academic Session Analysis'), ('CUSTOM', 'Custom Report')], db_index=True, max_length=30)),
                ('selected_columns', models.JSONField(default=list)),
                ('filters', models.JSONField(blank=True, default=dict)),
                ('format', models.CharField(choices=[('XLSX', 'Excel (.xlsx)'), ('CSV', 'CSV'), ('PDF', 'PDF')], default='XLSX', max_length=10)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('QUEUED', 'Queued'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], db_index=True, default='PENDING', max_length=20)),
                ('celery_task_id', models.CharField(blank=True, max_length=100)),
                ('file', models.FileField(blank=True, null=True, upload_to='reports/exports/')),
                ('file_size', models.PositiveIntegerField(blank=True, null=True)),
                ('row_count', models.PositiveIntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('academic_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='report_exports', to='programs.academicsession')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('program', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='report_exports', to='programs.program')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'report_export',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['program', 'status'], name='report_expo_program_ea68a9_idx'), models.Index(fields=['academic_session', 'status'], name='report_expo_academi_2d10b5_idx')],
            },
        ),
    ]
