# Generated by Django 5.2.6 on 2026-08-28 15:42

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('programs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('email', models.EmailField(db_index=True, max_length=254)),
                ('mobile', models.CharField(blank=True, db_index=True, max_length=20)),
                ('full_name', models.CharField(max_length=200)),
                ('employee_id', models.CharField(blank=True, max_length=50)),
                ('institution', models.CharField(blank=True, max_length=300)),
                ('institution_department', models.CharField(blank=True, max_length=200)),
                ('institution_designation', models.CharField(blank=True, max_length=200)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('country', models.CharField(blank=True, default='India', max_length=100)),
                ('extra_data', models.JSONField(blank=True, default=dict)),
                ('consent_given', models.BooleanField(default=False)),
                ('consent_date', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(blank=True, limit_choices_to={'category': 'ACADEMIC_DEPT'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='internal_participants', to='programs.masterdata')),
                ('designation', models.ForeignKey(blank=True, limit_choices_to={'category': 'DESIGNATION'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='participants_by_designation', to='programs.masterdata')),
                ('institution_type', models.ForeignKey(blank=True, limit_choices_to={'category': 'INSTITUTION_TYPE'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='external_participants', to='programs.masterdata')),
                ('participant_type', models.ForeignKey(blank=True, limit_choices_to={'category': 'PARTICIPANT_TYPE'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='participants', to='programs.masterdata')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='participant_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'participants_participant',
            },
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('registration_number', models.CharField(db_index=True, max_length=50, unique=True)),
                ('status', models.CharField(choices=[('SUBMITTED', 'Submitted'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('WAITLISTED', 'Waitlisted'), ('CANCELLED', 'Cancelled')], db_index=True, default='SUBMITTED', max_length=20)),
                ('form_data', models.JSONField(default=dict)),
                ('form_schema_version', models.JSONField(blank=True, default=dict)),
                ('identity_key_values', models.JSONField(default=dict)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('waitlist_position', models.PositiveIntegerField(blank=True, null=True)),
                ('promoted_at', models.DateTimeField(blank=True, null=True)),
                ('attendance_token', models.CharField(blank=True, max_length=64, unique=True)),
                ('feedback_token', models.CharField(blank=True, max_length=64, unique=True)),
                ('confirmation_sent', models.BooleanField(default=False)),
                ('confirmation_sent_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_registrations', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='participants.participant')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='programs.program')),
                ('promoted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promoted_registrations', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'participants_registration',
            },
        ),
        migrations.CreateModel(
            name='WaitlistPromotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promoted_at', models.DateTimeField(auto_now_add=True)),
                ('previous_position', models.PositiveIntegerField()),
                ('reason', models.TextField(blank=True)),
                ('promoted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('registration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotions', to='participants.registration')),
            ],
            options={
                'db_table': 'participants_waitlist_promotion',
                'ordering': ['-promoted_at'],
            },
        ),
        migrations.AddIndex(
            model_name='participant',
            index=models.Index(fields=['email', 'mobile'], name='participant_email_b608e7_idx'),
        ),
        migrations.AddIndex(
            model_name='participant',
            index=models.Index(fields=['participant_type'], name='participant_partici_a4c252_idx'),
        ),
        migrations.AddIndex(
            model_name='registration',
            index=models.Index(fields=['program', 'status'], name='participant_program_08dc01_idx'),
        ),
        migrations.AddIndex(
            model_name='registration',
            index=models.Index(fields=['participant', 'status'], name='participant_partici_b4259e_idx'),
        ),
        migrations.AddIndex(
            model_name='registration',
            index=models.Index(fields=['registration_number'], name='participant_registr_18f4ae_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='registration',
            unique_together={('program', 'participant')},
        ),
    ]
