# Generated by Django 5.2.6 on 2026-08-29 01:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0001_initial'),
        ('programs', '0002_alter_masterdata_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='internal_participants', to='programs.academicdepartment'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='designation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='participants_by_designation', to='programs.designation'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='institution_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='external_participants', to='programs.institutiontype'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='participant_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='participants', to='programs.participanttype'),
        ),
    ]
