# Generated by Django 5.2.6 on 2026-08-30 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0002_alter_participant_department_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='participant',
            name='participant_partici_a4c252_idx',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='institution_type',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='participant_type',
        ),
    ]
