# Generated by Django 5.2.6 on 2026-08-28 15:42

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('participants', '0001_initial'),
        ('programs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('trigger', models.CharField(choices=[('REG_CONFIRM', 'Registration Confirmation'), ('REG_APPROVAL', 'Registration Approval'), ('REG_REJECTION', 'Registration Rejection'), ('PROGRAM_REMINDER', 'Program Reminder'), ('FOOD_QR', 'Food QR Code'), ('FEEDBACK_INVITE', 'Feedback Invitation'), ('CERTIFICATE', 'Certificate Issued'), ('PROGRAM_CANCEL', 'Program Cancellation'), ('PROGRAM_RESCHEDULE', 'Program Reschedule'), ('WAITLIST_PROMO', 'Waitlist Promotion'), ('ATTENDANCE_MARKED', 'Attendance Marked')], db_index=True, max_length=30, unique=True)),
                ('channel', models.CharField(choices=[('EMAIL', 'Email'), ('SMS', 'SMS'), ('WHATSAPP', 'WhatsApp'), ('PUSH', 'Push Notification')], default='EMAIL', max_length=10)),
                ('subject_template', models.CharField(max_length=200)),
                ('html_template', models.TextField(help_text='MJML or HTML template with placeholders: {{participant_name}}, {{program_title}}, {{registration_number}}, {{qr_code}}, {{certificate_number}}, {{verification_url}}, etc.')),
                ('text_template', models.TextField(blank=True, help_text='Plain text fallback')),
                ('attach_qr', models.BooleanField(default=False)),
                ('attach_certificate', models.BooleanField(default=False)),
                ('attach_custom', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('is_system', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notification_template',
                'ordering': ['trigger'],
            },
        ),
        migrations.CreateModel(
            name='NotificationBatch',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('participant_filter', models.JSONField(blank=True, default=dict)),
                ('registration_filter', models.JSONField(blank=True, default=dict)),
                ('total', models.PositiveIntegerField(default=0)),
                ('sent', models.PositiveIntegerField(default=0)),
                ('failed', models.PositiveIntegerField(default=0)),
                ('pending', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('QUEUED', 'Queued'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('PARTIAL', 'Partial')], db_index=True, default='PENDING', max_length=20)),
                ('celery_task_id', models.CharField(blank=True, max_length=100)),
                ('result_summary', models.JSONField(blank=True, default=dict)),
                ('error_log', models.JSONField(blank=True, default=list)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_batches', to='programs.program')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='batches', to='notifications.notificationtemplate')),
            ],
            options={
                'db_table': 'notification_batch',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationMessage',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('subject', models.CharField(max_length=300)),
                ('html_content', models.TextField()),
                ('text_content', models.TextField(blank=True)),
                ('attachments', models.JSONField(blank=True, default=list)),
                ('channel', models.CharField(choices=[('EMAIL', 'Email'), ('SMS', 'SMS'), ('WHATSAPP', 'WhatsApp'), ('PUSH', 'Push Notification')], max_length=10)),
                ('recipient_address', models.CharField(max_length=300)),
                ('provider_message_id', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('QUEUED', 'Queued'), ('SENDING', 'Sending'), ('SENT', 'Sent'), ('FAILED', 'Failed'), ('BOUNCED', 'Bounced'), ('DELIVERED', 'Delivered'), ('OPENED', 'Opened'), ('CLICKED', 'Clicked')], db_index=True, default='PENDING', max_length=20)),
                ('status_details', models.JSONField(blank=True, default=dict)),
                ('idempotency_key', models.CharField(blank=True, db_index=True, max_length=100, unique=True)),
                ('retry_count', models.PositiveIntegerField(default=0)),
                ('max_retries', models.PositiveIntegerField(default=3)),
                ('next_retry_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('opened_at', models.DateTimeField(blank=True, null=True)),
                ('clicked_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_messages', to='participants.participant')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_messages', to='programs.program')),
                ('registration', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notification_messages', to='participants.registration')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='messages', to='notifications.notificationtemplate')),
            ],
            options={
                'db_table': 'notification_message',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['program', 'status'], name='notificatio_program_a26ec7_idx'), models.Index(fields=['participant', 'status'], name='notificatio_partici_48aa76_idx'), models.Index(fields=['template', 'status'], name='notificatio_templat_8e57ee_idx'), models.Index(fields=['idempotency_key'], name='notificatio_idempot_d86318_idx'), models.Index(fields=['status', 'next_retry_at'], name='notificatio_status_01c112_idx')],
            },
        ),
    ]
