# Generated by Django 5.2.6 on 2026-08-28 15:42

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('participants', '0001_initial'),
        ('programs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodService',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('service_type', models.CharField(choices=[('BREAKFAST', 'Breakfast'), ('LUNCH', 'Lunch'), ('DINNER', 'Dinner'), ('SNACKS', 'Snacks/Tea'), ('OTHER', 'Other')], db_index=True, max_length=20)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('eligibility_rule', models.JSONField(blank=True, default=dict, help_text="e.g., {'type': 'attendance_present'} or {'type': 'attendance_percentage', 'value': 50, 'reference_day': 1}")),
                ('service_time', models.TimeField(blank=True, null=True)),
                ('qr_valid_from', models.DateTimeField(blank=True, null=True)),
                ('qr_valid_until', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('qr_generated', models.BooleanField(default=False)),
                ('qr_generated_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food_services', to='programs.programday')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food_services', to='programs.program')),
                ('qr_generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_food_qrs', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'food_service',
            },
        ),
        migrations.CreateModel(
            name='FoodEligibility',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_eligible', models.BooleanField(db_index=True, default=False)),
                ('eligibility_basis', models.JSONField(blank=True, default=dict)),
                ('computed_at', models.DateTimeField(auto_now_add=True)),
                ('qr_generated', models.BooleanField(db_index=True, default=False)),
                ('qr_generated_at', models.DateTimeField(blank=True, null=True)),
                ('qr_sent', models.BooleanField(db_index=True, default=False)),
                ('qr_sent_at', models.DateTimeField(blank=True, null=True)),
                ('computed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='computed_food_eligibilities', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food_eligibilities', to='participants.participant')),
                ('qr_sent_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_food_qrs', to=settings.AUTH_USER_MODEL)),
                ('registration', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='food_eligibilities', to='participants.registration')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('food_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eligibilities', to='food.foodservice')),
            ],
            options={
                'db_table': 'food_eligibility',
            },
        ),
        migrations.CreateModel(
            name='FoodSummary',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('total_eligible', models.PositiveIntegerField(default=0)),
                ('qr_generated_count', models.PositiveIntegerField(default=0)),
                ('qr_sent_count', models.PositiveIntegerField(default=0)),
                ('claimed_count', models.PositiveIntegerField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('food_service', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='summary', to='food.foodservice')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'food_summary',
            },
        ),
        migrations.CreateModel(
            name='FoodToken',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token', models.CharField(db_index=True, max_length=64, unique=True)),
                ('is_claimed', models.BooleanField(db_index=True, default=False)),
                ('claimed_at', models.DateTimeField(blank=True, null=True)),
                ('claim_gate', models.CharField(blank=True, max_length=100)),
                ('claim_device_info', models.JSONField(blank=True, default=dict)),
                ('email_sent', models.BooleanField(default=False)),
                ('email_sent_at', models.DateTimeField(blank=True, null=True)),
                ('email_status', models.CharField(choices=[('PENDING', 'Pending'), ('SENT', 'Sent'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('email_error', models.TextField(blank=True)),
                ('claimed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='claimed_food_tokens', to=settings.AUTH_USER_MODEL)),
                ('eligibility', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='token', to='food.foodeligibility')),
                ('food_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tokens', to='food.foodservice')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food_tokens', to='participants.participant')),
            ],
            options={
                'db_table': 'food_token',
            },
        ),
        migrations.CreateModel(
            name='FoodClaim',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('claimed_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('gate_name', models.CharField(blank=True, max_length=100)),
                ('device_info', models.JSONField(blank=True, default=dict)),
                ('result', models.CharField(choices=[('SUCCESS', 'Success'), ('ALREADY_CLAIMED', 'Already Claimed'), ('NOT_ELIGIBLE', 'Not Eligible'), ('INVALID_TOKEN', 'Invalid Token'), ('WRONG_DAY', 'Wrong Day'), ('WRONG_SERVICE', 'Wrong Service'), ('EXPIRED', 'Expired')], default='SUCCESS', max_length=20)),
                ('claimed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_food_claims', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food_claims', to='participants.participant')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('food_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims', to='food.foodservice')),
                ('token', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims', to='food.foodtoken')),
            ],
            options={
                'db_table': 'food_claim',
            },
        ),
        migrations.AddIndex(
            model_name='foodservice',
            index=models.Index(fields=['program', 'day', 'is_active'], name='food_servic_program_57f068_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='foodservice',
            unique_together={('program', 'day', 'service_type')},
        ),
        migrations.AddIndex(
            model_name='foodeligibility',
            index=models.Index(fields=['food_service', 'is_eligible', 'qr_sent'], name='food_eligib_food_se_8f6cd1_idx'),
        ),
        migrations.AddIndex(
            model_name='foodeligibility',
            index=models.Index(fields=['participant', 'is_eligible'], name='food_eligib_partici_0b76f9_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='foodeligibility',
            unique_together={('food_service', 'participant')},
        ),
        migrations.AddIndex(
            model_name='foodtoken',
            index=models.Index(fields=['food_service', 'is_claimed'], name='food_token_food_se_88ff9a_idx'),
        ),
        migrations.AddIndex(
            model_name='foodtoken',
            index=models.Index(fields=['participant', 'is_claimed'], name='food_token_partici_bd8455_idx'),
        ),
        migrations.AddIndex(
            model_name='foodtoken',
            index=models.Index(fields=['token'], name='food_token_token_d9a20f_idx'),
        ),
        migrations.AddIndex(
            model_name='foodclaim',
            index=models.Index(fields=['food_service', 'claimed_at'], name='food_claim_food_se_84a9c8_idx'),
        ),
        migrations.AddIndex(
            model_name='foodclaim',
            index=models.Index(fields=['participant', 'claimed_at'], name='food_claim_partici_04f29b_idx'),
        ),
        migrations.AddIndex(
            model_name='foodclaim',
            index=models.Index(fields=['result', 'claimed_at'], name='food_claim_result_e8ccd1_idx'),
        ),
    ]
