# Generated by Django 5.2.6 on 2026-09-12 05:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
        ('participants', '0003_remove_participant_participant_partici_a4c252_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='foodtoken',
            constraint=models.UniqueConstraint(fields=('eligibility',), name='unique_eligibility_token'),
        ),
        migrations.AddConstraint(
            model_name='foodtoken',
            constraint=models.UniqueConstraint(fields=('token',), name='unique_food_token'),
        ),
    ]
