# Generated by Django 5.2.6 on 2026-08-28 15:42

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceGate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('location_info', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'db_table': 'attendance_gate',
            },
        ),
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_present', models.BooleanField(default=True)),
                ('is_late', models.BooleanField(default=False)),
                ('late_threshold_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('source', models.CharField(choices=[('SCAN', 'QR Scan'), ('MANUAL', 'Manual Entry'), ('IMPORT', 'Bulk Import'), ('CORRECTION', 'Manual Correction')], default='SCAN', max_length=20)),
                ('gate_name', models.CharField(blank=True, max_length=100)),
                ('device_info', models.JSONField(blank=True, default=dict)),
                ('marked_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('program_date', models.DateField(db_index=True)),
                ('is_corrected', models.BooleanField(default=False)),
                ('original_marked_at', models.DateTimeField(blank=True, null=True)),
                ('correction_reason', models.TextField(blank=True)),
                ('corrected_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'attendance_record',
            },
        ),
        migrations.CreateModel(
            name='AttendanceSession',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('ACTIVE', 'Active'), ('PAUSED', 'Paused'), ('CLOSED', 'Closed')], db_index=True, default='SCHEDULED', max_length=20)),
                ('opened_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('expected_participants', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'attendance_session',
            },
        ),
    ]
