# Generated by Django 5.2.6 on 2026-09-12 05:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_initial'),
        ('participants', '0003_remove_participant_participant_partici_a4c252_idx_and_more'),
        ('programs', '0010_remove_programday_feedback_enabled'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='attendancerecord',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='attendancerecord',
            name='source',
            field=models.CharField(choices=[('SCAN', 'QR Scan'), ('SELF', 'Self Check-in'), ('MANUAL', 'Manual Entry'), ('IMPORT', 'Bulk Import'), ('CORRECTION', 'Manual Correction')], default='SCAN', max_length=20),
        ),
        migrations.AddIndex(
            model_name='attendancerecord',
            index=models.Index(fields=['source', 'marked_at'], name='attendance__source_4e24de_idx'),
        ),
        migrations.AddConstraint(
            model_name='attendancerecord',
            constraint=models.UniqueConstraint(fields=('participant', 'day'), name='unique_participant_day_attendance'),
        ),
    ]
