# Generated by Django 5.2.6 on 2026-08-28 15:42

import django.db.models.deletion
import documents.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('programs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to=documents.models.document_upload_path)),
                ('original_filename', models.CharField(max_length=255)),
                ('file_size', models.PositiveIntegerField()),
                ('mime_type', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('CIRCULAR', 'Circular / Notification'), ('POSTER', 'Poster / Brochure'), ('PERMISSION_LETTER', 'Permission Letter'), ('RESOURCE_PERSON_PROFILE', 'Resource Person Profile'), ('PRESENTATION', 'Presentation / Slides'), ('ATTENDANCE_EVIDENCE', 'Attendance Evidence'), ('PHOTOGRAPHS', 'Photographs'), ('FEEDBACK_REPORT', 'Feedback Report'), ('PROGRAM_REPORT', 'Program Report'), ('CERTIFICATE_TEMPLATE', 'Certificate Template'), ('OTHER', 'Other')], db_index=True, default='OTHER', max_length=30)),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('version', models.PositiveIntegerField(default=1)),
                ('is_public', models.BooleanField(default=False)),
                ('allowed_roles', models.JSONField(blank=True, default=list)),
                ('is_validated', models.BooleanField(default=False)),
                ('validated_at', models.DateTimeField(blank=True, null=True)),
                ('validation_notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='programs.program')),
                ('replaces', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replaced_by', to='documents.document')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_documents', to=settings.AUTH_USER_MODEL)),
                ('validated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validated_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'document',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['program', 'category'], name='document_program_eddb67_idx'), models.Index(fields=['uploaded_by', 'created_at'], name='document_uploade_04d115_idx')],
            },
        ),
        migrations.CreateModel(
            name='GeneratedArtifact',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('artifact_type', models.CharField(choices=[('CERTIFICATE', 'Certificate PDF'), ('PROGRAM_REPORT', 'Program Report'), ('EXCEL_EXPORT', 'Excel Export'), ('QR_CODE', 'QR Code Image'), ('FEEDBACK_REPORT', 'Feedback Report')], db_index=True, max_length=20)),
                ('related_object_id', models.UUIDField(blank=True, null=True)),
                ('file', models.FileField(upload_to='artifacts/%Y/%m/%d/')),
                ('file_size', models.PositiveIntegerField()),
                ('access_token', models.CharField(blank=True, db_index=True, max_length=64, unique=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('download_count', models.PositiveIntegerField(default=0)),
                ('last_downloaded', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_artifacts', to=settings.AUTH_USER_MODEL)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_artifacts', to='programs.program')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'generated_artifact',
                'indexes': [models.Index(fields=['program', 'artifact_type'], name='generated_a_program_488c11_idx'), models.Index(fields=['access_token'], name='generated_a_access__1cdd65_idx')],
            },
        ),
    ]
