# Generated by Django 5.2.6 on 2026-08-28 15:42

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('participants', '0001_initial'),
        ('programs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackInstance',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scope', models.CharField(choices=[('PROGRAM', 'Program Level'), ('DAY', 'Day Level')], default='PROGRAM', max_length=10)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('schema', models.JSONField(blank=True, default=dict)),
                ('schema_version', models.JSONField(blank=True, default=dict)),
                ('is_anonymous', models.BooleanField(default=False)),
                ('allow_multiple', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('ACTIVE', 'Active'), ('CLOSED', 'Closed'), ('DISABLED', 'Disabled')], db_index=True, default='SCHEDULED', max_length=20)),
                ('opens_at', models.DateTimeField(blank=True, null=True)),
                ('closes_at', models.DateTimeField(blank=True, null=True)),
                ('public_token', models.CharField(blank=True, db_index=True, max_length=64, unique=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('day', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feedback_instances', to='programs.programday')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_instances', to='programs.program')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'feedback_instance',
            },
        ),
        migrations.CreateModel(
            name='FeedbackAnalytics',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('total_responses', models.PositiveIntegerField(default=0)),
                ('completion_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('average_rating', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('question_analytics', models.JSONField(blank=True, default=dict)),
                ('rating_distribution', models.JSONField(blank=True, default=dict)),
                ('comments', models.JSONField(blank=True, default=list)),
                ('last_computed', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('feedback_instance', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='feedback.feedbackinstance')),
            ],
            options={
                'db_table': 'feedback_analytics',
            },
        ),
        migrations.CreateModel(
            name='FeedbackResponse',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('answers', models.JSONField(default=dict)),
                ('is_anonymous', models.BooleanField(default=False)),
                ('submitted_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('completion_time_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('feedback_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='feedback.feedbackinstance')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_responses', to='participants.participant')),
                ('registration', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feedback_responses', to='participants.registration')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'feedback_response',
            },
        ),
        migrations.AddIndex(
            model_name='feedbackinstance',
            index=models.Index(fields=['program', 'status'], name='feedback_in_program_611c98_idx'),
        ),
        migrations.AddIndex(
            model_name='feedbackinstance',
            index=models.Index(fields=['public_token'], name='feedback_in_public__ba38df_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='feedbackinstance',
            unique_together={('program', 'day', 'scope')},
        ),
        migrations.AddIndex(
            model_name='feedbackresponse',
            index=models.Index(fields=['feedback_instance', 'submitted_at'], name='feedback_re_feedbac_500e96_idx'),
        ),
        migrations.AddIndex(
            model_name='feedbackresponse',
            index=models.Index(fields=['participant', 'submitted_at'], name='feedback_re_partici_bf2ab4_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='feedbackresponse',
            unique_together={('feedback_instance', 'participant')},
        ),
    ]
