# Generated by Django 5.2.6 on 2026-08-28 15:42

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('certificate_number', models.CharField(db_index=True, max_length=50, unique=True)),
                ('verification_token', models.CharField(db_index=True, max_length=64, unique=True)),
                ('status', models.CharField(choices=[('GENERATED', 'Generated'), ('SENT', 'Sent'), ('CANCELLED', 'Cancelled'), ('EXPIRED', 'Expired')], db_index=True, default='GENERATED', max_length=20)),
                ('eligibility_data', models.JSONField(blank=True, default=dict)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='certificates/pdfs/')),
                ('pdf_generated_at', models.DateTimeField(blank=True, null=True)),
                ('email_sent', models.BooleanField(default=False)),
                ('email_sent_at', models.DateTimeField(blank=True, null=True)),
                ('email_status', models.CharField(choices=[('PENDING', 'Pending'), ('SENT', 'Sent'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('email_error', models.TextField(blank=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancellation_reason', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'certificate',
            },
        ),
        migrations.CreateModel(
            name='CertificateBatchJob',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('job_type', models.CharField(choices=[('GENERATE', 'Generate'), ('SEND', 'Send'), ('REGENERATE', 'Regenerate')], max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('PARTIAL', 'Partial')], db_index=True, default='PENDING', max_length=20)),
                ('total', models.PositiveIntegerField(default=0)),
                ('processed', models.PositiveIntegerField(default=0)),
                ('succeeded', models.PositiveIntegerField(default=0)),
                ('failed', models.PositiveIntegerField(default=0)),
                ('parameters', models.JSONField(blank=True, default=dict)),
                ('result_summary', models.JSONField(blank=True, default=dict)),
                ('error_log', models.JSONField(blank=True, default=list)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'certificate_batch_job',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CertificateConfig',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('eligibility_rule', models.JSONField(blank=True, default=dict, help_text="\n        Examples:\n        - {'type': 'attendance_percentage', 'min_percentage': 75}\n        - {'type': 'min_days_present', 'min_days': 3, 'total_days': 5}\n        - {'type': 'required_days', 'day_numbers': [1, 3, 5]}\n        - {'type': 'registration_only'}\n        - {'type': 'custom', 'expression': 'attendance_rate >= 0.75 AND day_1_present AND day_3_present'}\n        ")),
                ('certificate_prefix', models.CharField(default='CERT', max_length=20)),
                ('start_number', models.PositiveIntegerField(default=1)),
                ('current_number', models.PositiveIntegerField(default=1)),
                ('auto_generate', models.BooleanField(default=False)),
                ('auto_send', models.BooleanField(default=False)),
                ('require_manual_approval', models.BooleanField(default=True)),
                ('validity_years', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'certificate_config',
            },
        ),
        migrations.CreateModel(
            name='CertificateTemplate',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('html_template', models.TextField(help_text='HTML template with placeholders: {{participant_name}}, {{program_title}}, {{program_dates}}, {{certificate_number}}, {{issue_date}}, {{qr_code}}, {{signatures}}')),
                ('css_styles', models.TextField(blank=True)),
                ('page_size', models.CharField(choices=[('A4', 'A4'), ('A5', 'A5'), ('LETTER', 'Letter'), ('LEGAL', 'Legal')], default='A4', max_length=20)),
                ('orientation', models.CharField(choices=[('portrait', 'Portrait'), ('landscape', 'Landscape')], default='portrait', max_length=10)),
                ('signatory_1_name', models.CharField(blank=True, max_length=200)),
                ('signatory_1_title', models.CharField(blank=True, max_length=200)),
                ('signatory_1_signature', models.ImageField(blank=True, null=True, upload_to='signatures/')),
                ('signatory_2_name', models.CharField(blank=True, max_length=200)),
                ('signatory_2_title', models.CharField(blank=True, max_length=200)),
                ('signatory_2_signature', models.ImageField(blank=True, null=True, upload_to='signatures/')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='certificates/logos/')),
                ('watermark', models.ImageField(blank=True, null=True, upload_to='certificates/watermarks/')),
                ('is_default', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'certificate_template',
                'ordering': ['-is_default', 'name'],
            },
        ),
    ]
