# Generated by Django 5.2.6 on 2026-08-30 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificatebatchjob',
            name='celery_task_id',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
